import type { ContextPacketItem, DeltaContextPacket } from "@continuum/shared";

export const ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION = "continuum.assist-context.v1" as const;
export interface AssistEnvelopeItem { contextItemVersionId:string; sourcePath:string; symbol:string|null; startLine:number; endLine:number; requirementState:"required"|"recommended"|"optional"|"not_applicable"|"unavailable"|"unknown_legacy"; packetSection:"orientation"|"exact_implementation"|"mandatory_contracts_constraints"|"directly_related_tests"|"optional_context"|"unknown_legacy"; coverageCategories:string[]; selectionReasons:string[]; exactMatchReason:string|null; relationshipReason:string|null; coverageReason:string|null; contentHash:string; estimatedTokens:number; content:string; }
export interface AssistEnvelopeReference { contextItemVersionId:string; sourcePath:string; symbol:string|null; startLine:number; endLine:number; contentHash:string; estimatedTokensAvoided:number; }
export interface AssistContextEnvelope { schemaVersion:typeof ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION; session:{id:string;repositoryId:number;snapshotKind:"commit"|"worktree";baseCommitHash:string;worktreeHash:string|null;strategyId:string;strategyVersion:string}; budget:{initialEstimatedTokens:number;maximumSessionEstimatedTokens:number;deliveredEstimatedTokens:number;activeEstimatedTokens:number;remainingEstimatedTokens:number}; items:AssistEnvelopeItem[]; references:AssistEnvelopeReference[]; omittedItems:Array<{contextItemVersionId:string|null;sourcePath:string|null;omissionReason:string;estimatedTokens:number}>; coverage:{added:string[];remaining:string[];incomplete:boolean;additionalEstimatedTokensRequired:number|null}; }
export interface AssistEnvelopeSession { repositoryId:number;snapshotKind:"commit"|"worktree";baseCommitHash:string;worktreeHash:string|null;maximumSessionEstimatedTokens:number;deliveredEstimatedTokens:number;activeEstimatedTokens:number;remainingEstimatedTokens:number; }

function item(value:ContextPacketItem,stage:DeltaContextPacket["stage"]):AssistEnvelopeItem { const version=value.candidate.item; return {contextItemVersionId:version.id,sourcePath:version.source_path,symbol:version.symbol_name,startLine:version.source_start_line,endLine:version.source_end_line,requirementState:"unknown_legacy",packetSection:stage==="orientation"?"orientation":"unknown_legacy",coverageCategories:[...value.candidate.coverageCategories].sort(),selectionReasons:[...value.candidate.reasons].sort(),exactMatchReason:null,relationshipReason:null,coverageReason:null,contentHash:version.content_hash,estimatedTokens:value.candidate.estimatedTokens,content:value.content}; }
function reference(value:DeltaContextPacket["activeReferences"][number]):AssistEnvelopeReference{return {contextItemVersionId:value.contextItemVersionId,sourcePath:value.sourcePath,symbol:null,startLine:0,endLine:0,contentHash:value.contentHash,estimatedTokensAvoided:value.estimatedTokens};}
function canonicalize(value:unknown):unknown{if(Array.isArray(value))return value.map(canonicalize);if(value!==null&&typeof value==="object"){const record=value as Record<string,unknown>;return Object.fromEntries(Object.keys(record).sort().map((key)=>[key,canonicalize(record[key])]));}return value;}
export function serializeAssistContextEnvelope(envelope:AssistContextEnvelope):string{return JSON.stringify(canonicalize(envelope));}
export function parseAssistContextEnvelope(serialized:string):AssistContextEnvelope{const parsed:unknown=JSON.parse(serialized);if(parsed===null||typeof parsed!=="object"||Array.isArray(parsed)||(parsed as Record<string,unknown>)["schemaVersion"]!==ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION)throw new Error("Invalid Continuum assist context envelope.");return parsed as AssistContextEnvelope;}
export function createAssistContextEnvelope(packet:DeltaContextPacket,session?:AssistEnvelopeSession):AssistContextEnvelope{const snapshot=packet.newItems[0]?.candidate.provenance.snapshot??packet.restoredItems[0]?.candidate.provenance.snapshot;const repositoryId=session?.repositoryId??packet.newItems[0]?.candidate.provenance.repositoryId??0;const maximum=session?.maximumSessionEstimatedTokens??packet.estimatedNewTokens+packet.estimatedRestoredTokens;const delivered=session?.deliveredEstimatedTokens??packet.estimatedNewTokens+packet.estimatedRestoredTokens;const active=session?.activeEstimatedTokens??packet.activeReferences.reduce((total,entry)=>total+entry.estimatedTokens,0);const remaining=session?.remainingEstimatedTokens??Math.max(0,maximum-delivered);return {schemaVersion:ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION,session:{id:packet.sessionId,repositoryId,snapshotKind:session?.snapshotKind??snapshot?.snapshot_kind??"commit",baseCommitHash:session?.baseCommitHash??snapshot?.base_commit_hash??"",worktreeHash:session?.worktreeHash??snapshot?.worktree_hash??null,strategyId:packet.strategyId,strategyVersion:packet.strategyVersion},budget:{initialEstimatedTokens:packet.estimatedNewTokens+packet.estimatedRestoredTokens,maximumSessionEstimatedTokens:maximum,deliveredEstimatedTokens:delivered,activeEstimatedTokens:active,remainingEstimatedTokens:remaining},items:[...packet.newItems,...packet.restoredItems].map((entry)=>item(entry,packet.stage)).sort((left,right)=>left.contextItemVersionId.localeCompare(right.contextItemVersionId)),references:packet.activeReferences.map(reference).sort((left,right)=>left.contextItemVersionId.localeCompare(right.contextItemVersionId)),omittedItems:packet.omittedItems.map((entry)=>({contextItemVersionId:entry.contextItemVersionId,sourcePath:null,omissionReason:entry.reason,estimatedTokens:entry.estimatedTokens})).sort((left,right)=>(left.contextItemVersionId??"").localeCompare(right.contextItemVersionId??"")),coverage:{added:[...packet.coverageAdded].sort(),remaining:[...packet.coverageRemaining].sort(),incomplete:packet.incomplete,additionalEstimatedTokensRequired:packet.additionalEstimatedTokensRequired??null}};}
export function buildContextEnvelope(packet:DeltaContextPacket,session?:AssistEnvelopeSession):string{return serializeAssistContextEnvelope(createAssistContextEnvelope(packet,session));}
