import type { ContextPacketItem, DeltaContextPacket } from "@continuum/shared";
import { isRecord } from "./json.js";

export const ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION = "continuum.assist-context.v1" as const;
export interface AssistEnvelopeItem { contextItemVersionId:string; sourcePath:string; symbol:string|null; startLine:number; endLine:number; requirementState:"required"|"recommended"|"optional"|"not_applicable"|"unavailable"|"unknown_legacy"; packetSection:"orientation"|"exact_implementation"|"mandatory_contracts_constraints"|"directly_related_tests"|"optional_context"|"unknown_legacy"; coverageCategories:string[]; selectionReasons:string[]; exactMatchReason:string|null; relationshipReason:string|null; coverageReason:string|null; contentHash:string; estimatedTokens:number; content:string; }
export interface AssistEnvelopeReference { contextItemVersionId:string; sourcePath:string; symbol:string|null; startLine:number; endLine:number; contentHash:string; estimatedTokensAvoided:number; }
export interface AssistContextEnvelope { schemaVersion:typeof ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION; session:{id:string;repositoryId:number;snapshotKind:"commit"|"worktree";baseCommitHash:string;worktreeHash:string|null;strategyId:string;strategyVersion:string}; budget:{initialEstimatedTokens:number;maximumSessionEstimatedTokens:number;deliveredEstimatedTokens:number;activeEstimatedTokens:number;remainingEstimatedTokens:number}; items:AssistEnvelopeItem[]; references:AssistEnvelopeReference[]; omittedItems:Array<{contextItemVersionId:string|null;sourcePath:string|null;omissionReason:string;estimatedTokens:number}>; coverage:{added:string[];remaining:string[];incomplete:boolean;additionalEstimatedTokensRequired:number|null}; }
export interface AssistEnvelopeSession { repositoryId:number;snapshotKind:"commit"|"worktree";baseCommitHash:string;worktreeHash:string|null;maximumSessionEstimatedTokens:number;deliveredEstimatedTokens:number;activeEstimatedTokens:number;remainingEstimatedTokens:number; }

function item(value:ContextPacketItem,stage:DeltaContextPacket["stage"]):AssistEnvelopeItem { const version=value.candidate.item; const categories=[...value.candidate.coverageCategories].sort(); const requirementState=categories.some((category)=>category==="implementation"||category==="security_constraint"||category==="public_contract"||category==="database_schema"||category==="rollback")?"required":categories.includes("tests")?"recommended":"optional"; const packetSection=categories.includes("security_constraint")||categories.includes("database_schema")||categories.includes("rollback")?"mandatory_contracts_constraints":categories.includes("implementation")?"exact_implementation":categories.includes("tests")?"directly_related_tests":stage==="orientation"?"orientation":"optional_context"; return {contextItemVersionId:version.id,sourcePath:version.source_path,symbol:version.symbol_name,startLine:version.source_start_line,endLine:version.source_end_line,requirementState,packetSection,coverageCategories:categories,selectionReasons:[...value.candidate.reasons].sort(),exactMatchReason:null,relationshipReason:null,coverageReason:null,contentHash:version.content_hash,estimatedTokens:value.candidate.estimatedTokens,content:value.content}; }
function reference(value:DeltaContextPacket["activeReferences"][number]):AssistEnvelopeReference{return {contextItemVersionId:value.contextItemVersionId,sourcePath:value.sourcePath,symbol:null,startLine:0,endLine:0,contentHash:value.contentHash,estimatedTokensAvoided:value.estimatedTokens};}
function canonicalize(value:unknown):unknown{if(Array.isArray(value))return value.map(canonicalize);if(value!==null&&typeof value==="object"){const record=value as Record<string,unknown>;return Object.fromEntries(Object.keys(record).sort().map((key)=>[key,canonicalize(record[key])]));}return value;}
export function serializeCanonical(value:unknown):string{return JSON.stringify(canonicalize(value));}
export function serializeAssistContextEnvelope(envelope:AssistContextEnvelope):string{return JSON.stringify(canonicalize(envelope));}
const exactKeys=(record:Record<string,unknown>,keys:string[]):boolean=>Object.keys(record).length===keys.length&&keys.every((key)=>Object.prototype.hasOwnProperty.call(record,key));
const nonEmpty=(value:unknown):value is string=>typeof value==="string"&&value.length>0;
const integer=(value:unknown):value is number=>typeof value==="number"&&Number.isInteger(value);
const relativePath=(value:unknown):value is string=>nonEmpty(value)&&!value.startsWith("/")&&!/^[A-Za-z]:[\\/]/.test(value)&&!value.startsWith("\\\\")&&!value.split(/[\\/]/).includes("..");
const stringArray=(value:unknown):value is string[]=>Array.isArray(value)&&value.every((entry)=>typeof entry==="string");
const states=new Set<AssistEnvelopeItem["requirementState"]>(["required","recommended","optional","not_applicable","unavailable","unknown_legacy"]);
const sections=new Set<AssistEnvelopeItem["packetSection"]>(["orientation","exact_implementation","mandatory_contracts_constraints","directly_related_tests","optional_context","unknown_legacy"]);
export const itemValid=(value:unknown):value is AssistEnvelopeItem=>{if(!isRecord(value)||!exactKeys(value,["contextItemVersionId","sourcePath","symbol","startLine","endLine","requirementState","packetSection","coverageCategories","selectionReasons","exactMatchReason","relationshipReason","coverageReason","contentHash","estimatedTokens","content"]))return false;return nonEmpty(value["contextItemVersionId"])&&relativePath(value["sourcePath"])&&(value["symbol"]===null||typeof value["symbol"]==="string")&&integer(value["startLine"])&&value["startLine"]>=1&&integer(value["endLine"])&&value["endLine"]>=value["startLine"]&&typeof value["requirementState"]==="string"&&states.has(value["requirementState"] as AssistEnvelopeItem["requirementState"])&&typeof value["packetSection"]==="string"&&sections.has(value["packetSection"] as AssistEnvelopeItem["packetSection"])&&stringArray(value["coverageCategories"])&&stringArray(value["selectionReasons"])&&(value["exactMatchReason"]===null||typeof value["exactMatchReason"]==="string")&&(value["relationshipReason"]===null||typeof value["relationshipReason"]==="string")&&(value["coverageReason"]===null||typeof value["coverageReason"]==="string")&&nonEmpty(value["contentHash"])&&integer(value["estimatedTokens"])&&value["estimatedTokens"]>=0&&typeof value["content"]==="string";};
export const referenceValid=(value:unknown):value is AssistEnvelopeReference=>isRecord(value)&&exactKeys(value,["contextItemVersionId","sourcePath","symbol","startLine","endLine","contentHash","estimatedTokensAvoided"])&&nonEmpty(value["contextItemVersionId"])&&relativePath(value["sourcePath"])&&(value["symbol"]===null||typeof value["symbol"]==="string")&&integer(value["startLine"])&&integer(value["endLine"])&&((value["startLine"]===0&&value["endLine"]===0)||(value["startLine"]>=1&&value["endLine"]>=value["startLine"]))&&nonEmpty(value["contentHash"])&&integer(value["estimatedTokensAvoided"])&&value["estimatedTokensAvoided"]>=0;
const envelopeValid=(value:unknown):value is AssistContextEnvelope=>{if(!isRecord(value)||!exactKeys(value,["schemaVersion","session","budget","items","references","omittedItems","coverage"])||value["schemaVersion"]!==ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION||!isRecord(value["session"])||!isRecord(value["budget"])||!isRecord(value["coverage"]))return false;const session=value["session"],budget=value["budget"],coverage=value["coverage"];if(!exactKeys(session,["id","repositoryId","snapshotKind","baseCommitHash","worktreeHash","strategyId","strategyVersion"])||!nonEmpty(session["id"])||!integer(session["repositoryId"])||session["repositoryId"]<0||(session["snapshotKind"]!=="commit"&&session["snapshotKind"]!=="worktree")||!nonEmpty(session["baseCommitHash"])||(session["worktreeHash"]!==null&&typeof session["worktreeHash"]!=="string")||!nonEmpty(session["strategyId"])||!nonEmpty(session["strategyVersion"]))return false;if(!exactKeys(budget,["initialEstimatedTokens","maximumSessionEstimatedTokens","deliveredEstimatedTokens","activeEstimatedTokens","remainingEstimatedTokens"]))return false;const numeric=[budget["initialEstimatedTokens"],budget["maximumSessionEstimatedTokens"],budget["deliveredEstimatedTokens"],budget["activeEstimatedTokens"],budget["remainingEstimatedTokens"]];if(!numeric.every((entry)=>integer(entry)&&Number(entry)>=0)||Number(budget["deliveredEstimatedTokens"])>Number(budget["maximumSessionEstimatedTokens"])||Number(budget["remainingEstimatedTokens"])>Number(budget["maximumSessionEstimatedTokens"]))return false;if(!Array.isArray(value["items"])||!value["items"].every(itemValid)||!Array.isArray(value["references"])||!value["references"].every(referenceValid)||!Array.isArray(value["omittedItems"])||!value["omittedItems"].every((entry)=>isRecord(entry)&&exactKeys(entry,["contextItemVersionId","sourcePath","omissionReason","estimatedTokens"])&&(entry["contextItemVersionId"]===null||nonEmpty(entry["contextItemVersionId"]))&&(entry["sourcePath"]===null||relativePath(entry["sourcePath"]))&&nonEmpty(entry["omissionReason"])&&integer(entry["estimatedTokens"])&&Number(entry["estimatedTokens"])>=0))return false;return exactKeys(coverage,["added","remaining","incomplete","additionalEstimatedTokensRequired"])&&stringArray(coverage["added"])&&stringArray(coverage["remaining"])&&typeof coverage["incomplete"]==="boolean"&&(coverage["additionalEstimatedTokensRequired"]===null||(integer(coverage["additionalEstimatedTokensRequired"])&&Number(coverage["additionalEstimatedTokensRequired"])>=0));};
export function parseAssistContextEnvelope(serialized:string):AssistContextEnvelope{const parsed:unknown=JSON.parse(serialized);if(!envelopeValid(parsed))throw new Error("Invalid Continuum assist context envelope.");return parsed;}
export function createAssistContextEnvelope(packet:DeltaContextPacket,session?:AssistEnvelopeSession):AssistContextEnvelope{const snapshot=packet.newItems[0]?.candidate.provenance.snapshot??packet.restoredItems[0]?.candidate.provenance.snapshot;const repositoryId=session?.repositoryId??packet.newItems[0]?.candidate.provenance.repositoryId??0;const maximum=session?.maximumSessionEstimatedTokens??packet.estimatedNewTokens+packet.estimatedRestoredTokens;const delivered=session?.deliveredEstimatedTokens??packet.estimatedNewTokens+packet.estimatedRestoredTokens;const active=session?.activeEstimatedTokens??packet.activeReferences.reduce((total,entry)=>total+entry.estimatedTokens,0);const remaining=session?.remainingEstimatedTokens??Math.max(0,maximum-delivered);return {schemaVersion:ASSIST_CONTEXT_ENVELOPE_SCHEMA_VERSION,session:{id:packet.sessionId,repositoryId,snapshotKind:session?.snapshotKind??snapshot?.snapshot_kind??"commit",baseCommitHash:session?.baseCommitHash??snapshot?.base_commit_hash??"",worktreeHash:session?.worktreeHash??snapshot?.worktree_hash??null,strategyId:packet.strategyId,strategyVersion:packet.strategyVersion},budget:{initialEstimatedTokens:packet.estimatedNewTokens+packet.estimatedRestoredTokens,maximumSessionEstimatedTokens:maximum,deliveredEstimatedTokens:delivered,activeEstimatedTokens:active,remainingEstimatedTokens:remaining},items:[...packet.newItems,...packet.restoredItems].map((entry)=>item(entry,packet.stage)).sort((left,right)=>left.contextItemVersionId.localeCompare(right.contextItemVersionId)),references:packet.activeReferences.map(reference).sort((left,right)=>left.contextItemVersionId.localeCompare(right.contextItemVersionId)),omittedItems:packet.omittedItems.map((entry)=>({contextItemVersionId:entry.contextItemVersionId,sourcePath:null,omissionReason:entry.reason,estimatedTokens:entry.estimatedTokens})).sort((left,right)=>(left.contextItemVersionId??"").localeCompare(right.contextItemVersionId??"")),coverage:{added:[...packet.coverageAdded].sort(),remaining:[...packet.coverageRemaining].sort(),incomplete:packet.incomplete,additionalEstimatedTokensRequired:packet.additionalEstimatedTokensRequired??null}};}
export function buildContextEnvelope(packet:DeltaContextPacket,session?:AssistEnvelopeSession):string{return serializeAssistContextEnvelope(createAssistContextEnvelope(packet,session));}
