import { ContextSessionRepository, IndexRunRepository, RepositoryRepository, type ContextSessionRow, type Db } from "@continuum/database";
import { resolveSnapshotIdentity } from "@continuum/git-analyzer";
import { snapshotsEqual } from "@continuum/shared";
import type { AdaptiveContextController, AgentContextRequest, ContextCandidate, ContextControlDecision, ContextControlSignal, ContextCoverageCategory, ContextSession, ContextSessionResult, CreateContextSessionInput, DeltaContextPacket, IndexSnapshotIdentity } from "@continuum/shared";
import { ContextEngine } from "../engine.js";
import { DeterministicDeltaPacketBuilder } from "./delta-packet-builder.js";
import { ContextEscalationLimitError, IndexedSnapshotMismatchError, RepositoryNotIndexedError } from "./session-errors.js";
import { DEFAULT_ESCALATION_LIMITS, queryForSignal, STRATEGY_ID, STRATEGY_VERSION } from "./escalation-policy.js";
export const INITIAL_DELIVERY_POLICY={orientationBudgetTokens:250,exactImplementationBudgetTokens:700,mandatoryContextReserveTokens:350,directTestReserveTokens:350,optionalContextCeilingTokens:250,maximumInitialTokens:1900,maximumInitialItems:12} as const;
const snapshotFrom=(row:ContextSessionRow):IndexSnapshotIdentity=>({snapshot_kind:row.snapshot_kind,base_commit_hash:row.base_commit_hash,worktree_hash:row.worktree_hash,dirty:row.snapshot_kind==="worktree"});
const domainFrom=(row:ContextSessionRow):ContextSession=>({id:row.id,repositoryId:row.repository_id,...(row.run_id?{runId:row.run_id}:{}),task:JSON.parse(row.task_analysis_json),snapshot:snapshotFrom(row),strategyId:row.strategy_id,strategyVersion:row.strategy_version,status:row.status,maximumEstimatedTokens:row.maximum_estimated_tokens,deliveredEstimatedTokens:row.delivered_estimated_tokens,activeEstimatedTokens:row.active_estimated_tokens,remainingEstimatedTokens:row.remaining_estimated_tokens,createdAt:row.created_at,updatedAt:row.updated_at,...(row.completed_at?{completedAt:row.completed_at}:{})});
function prioritize(candidates:ContextCandidate[],symbols:string[]=[],paths:string[]=[],coverage:ContextCoverageCategory[]=[]):ContextCandidate[]{return [...candidates].sort((a,b)=>{const weight=(candidate:ContextCandidate)=>{let value=candidate.score;if(symbols.some(symbol=>candidate.item.symbol_name===symbol))value+=100;if(paths.some(path=>candidate.item.source_path.endsWith(path)))value+=80;if(candidate.coverageCategories.some(category=>coverage.includes(category)))value+=40;if(candidate.coverageCategories.includes("security_constraint"))value+=20;if(candidate.coverageCategories.includes("implementation"))value+=10;if(candidate.coverageCategories.includes("public_contract"))value+=8;if(candidate.coverageCategories.includes("tests"))value+=6;return value;};return weight(b)-weight(a)||a.item.id.localeCompare(b.item.id);});}
export class DeterministicAdaptiveContextController implements AdaptiveContextController {
 private readonly sessions:ContextSessionRepository;private readonly builder:DeterministicDeltaPacketBuilder;
 constructor(private readonly db:Db){this.sessions=new ContextSessionRepository(db);this.builder=new DeterministicDeltaPacketBuilder(this.sessions);}
 private async loadActive(id:string){const row=this.sessions.findRequired(id),session=domainFrom(row),current=await resolveSnapshotIdentity((new RepositoryRepository(this.db).findByPath as any)?(this.db.prepare("SELECT canonical_path FROM repositories WHERE id=?").get(session.repositoryId) as {canonical_path:string}).canonical_path:"");return{session,current,engine:new ContextEngine(this.db,session.repositoryId,current)};}
 async createSession(input:CreateContextSessionInput):Promise<ContextSession>{const repository=new RepositoryRepository(this.db).findByPath(input.repositoryRoot);if(!repository||repository.id!==input.repositoryId)throw new RepositoryNotIndexedError(input.repositoryId);const current=await resolveSnapshotIdentity(input.repositoryRoot),indexed=new IndexRunRepository(this.db).findLatestSuccessful(input.repositoryId);if(!indexed)throw new RepositoryNotIndexedError(input.repositoryId);const indexedSnapshot:IndexSnapshotIdentity={snapshot_kind:indexed.snapshot_kind as "commit"|"worktree",base_commit_hash:indexed.base_commit_hash,worktree_hash:indexed.worktree_hash,dirty:indexed.snapshot_kind==="worktree"};if(!snapshotsEqual(current,indexedSnapshot))throw new IndexedSnapshotMismatchError();const engine=new ContextEngine(this.db,input.repositoryId,current),analysis=engine.analyze(input.task);const row=this.sessions.create({repositoryId:input.repositoryId,runId:input.runId,taskText:input.task,taskAnalysisJson:JSON.stringify(analysis),snapshot:current,strategyId:STRATEGY_ID,strategyVersion:STRATEGY_VERSION,maximumEstimatedTokens:input.maximumEstimatedTokens??8000});return domainFrom(this.sessions.activate(row.id));}
 async createInitialDelivery(sessionId:string):Promise<DeltaContextPacket>{const{session,current,engine}=await this.loadActive(sessionId);const packet=await engine.packet(session.task.originalTask);const candidates=[...(packet.orientation.items),...(packet.implementation.items)].map(item=>item.candidate);const mandatory=packet.coverage.coverageEvidence.filter(entry=>entry.state==="required"&&entry.matchingIndexedCandidateCount>0).map(entry=>entry.category);return this.builder.build(session,candidates,{stage:"orientation",trigger:"initial",reason:"Budgeted initial context.",reasons:["Selected section-budgeted orientation, exact implementation, mandatory constraints, directly related tests, and bounded optional context."],currentSnapshot:current,maximumEstimatedTokens:Math.min(INITIAL_DELIVERY_POLICY.maximumInitialTokens,session.remainingEstimatedTokens),maximumItems:INITIAL_DELIVERY_POLICY.maximumInitialItems,mandatoryCoverage:mandatory});}
 async requestContext(sessionId:string,request:AgentContextRequest):Promise<DeltaContextPacket>{const{session,current,engine}=await this.loadActive(sessionId);if(this.sessions.countEscalations(sessionId)>=DEFAULT_ESCALATION_LIMITS.maximumEscalations)throw new ContextEscalationLimitError(DEFAULT_ESCALATION_LIMITS.maximumEscalations);const signal=this.sessions.recordSignal(sessionId,{type:"agent_context_request",...request});const query=[request.query,...(request.requestedSymbols??[]),...(request.requestedPaths??[])].join(" ");const candidates=prioritize(await engine.search(query,{limit:50}),request.requestedSymbols,request.requestedPaths,request.requestedCoverage);return this.builder.build(session,candidates,{stage:"escalation",trigger:"agent_request",reason:"Explicit context request.",reasons:["Exact symbols and paths precede requested coverage and ranked lexical matches."],currentSnapshot:current,maximumEstimatedTokens:Math.min(DEFAULT_ESCALATION_LIMITS.maximumEstimatedTokensPerEscalation,session.remainingEstimatedTokens),maximumItems:DEFAULT_ESCALATION_LIMITS.maximumItemsPerEscalation,mandatoryCoverage:request.requestedCoverage,signalId:signal.id,minimumCandidateScore:DEFAULT_ESCALATION_LIMITS.minimumCandidateScore});}
 async reportSignal(sessionId:string,signal:ContextControlSignal):Promise<DeltaContextPacket|ContextControlDecision>{if(signal.type==="agent_context_request")return this.requestContext(sessionId,signal);const{session,current,engine}=await this.loadActive(sessionId);if(this.sessions.countEscalations(sessionId)>=DEFAULT_ESCALATION_LIMITS.maximumEscalations)throw new ContextEscalationLimitError(DEFAULT_ESCALATION_LIMITS.maximumEscalations);const stored=this.sessions.recordSignal(sessionId,signal),policy=queryForSignal(signal),candidates=prioritize(await engine.search(policy.query,{limit:50}),signal.type==="test_failure"?signal.relatedSymbols:[],signal.type==="test_failure"?signal.relatedPaths:signal.type==="out_of_scope_modification"?signal.modifiedPaths:[],policy.coverage);return this.builder.build(session,candidates,{stage:"escalation",trigger:signal.type,reason:policy.reasons[0]??"Deterministic signal escalation.",reasons:policy.reasons,currentSnapshot:current,maximumEstimatedTokens:Math.min(DEFAULT_ESCALATION_LIMITS.maximumEstimatedTokensPerEscalation,session.remainingEstimatedTokens),maximumItems:DEFAULT_ESCALATION_LIMITS.maximumItemsPerEscalation,mandatoryCoverage:policy.coverage,signalId:stored.id,minimumCandidateScore:DEFAULT_ESCALATION_LIMITS.minimumCandidateScore});}
 async completeSession(sessionId:string,result:ContextSessionResult):Promise<ContextSession>{return domainFrom(this.sessions.complete(sessionId,result.status));}
}
