import type { ContextSessionRepository } from "@continuum/database";
import type { ContextCandidate, ContextCoverageCategory, ContextDeliveryTrigger, ContextPacketItem, ContextPacketOmission, ContextReference, ContextSession, DeltaContextPacket, IndexSnapshotIdentity } from "@continuum/shared";
import { DEFAULT_ESCALATION_LIMITS, STRATEGY_ID, STRATEGY_VERSION } from "./escalation-policy.js";
export interface DeltaPacketBuildOptions { stage: "orientation" | "implementation" | "escalation"; trigger: ContextDeliveryTrigger; reason: string; reasons: string[]; currentSnapshot: IndexSnapshotIdentity; maximumEstimatedTokens?: number; maximumItems?: number; mandatoryCoverage?: ContextCoverageCategory[]; signalId?: string; minimumCandidateScore?: number; }
export interface DeltaPacketBuilder { build(session: ContextSession,candidates:ContextCandidate[],options:DeltaPacketBuildOptions):Promise<DeltaContextPacket>; }
export class DeterministicDeltaPacketBuilder implements DeltaPacketBuilder {
 constructor(private readonly sessions:ContextSessionRepository){}
 async build(session:ContextSession,candidates:ContextCandidate[],options:DeltaPacketBuildOptions):Promise<DeltaContextPacket>{
  const active=this.sessions.findActiveItems(session.id),byVersion=new Map(active.map(item=>[item.context_item_version_id,item])),byHash=new Map(active.map(item=>[item.content_hash,item]));
  const newItems:ContextPacketItem[]=[],activeReferences:ContextReference[]=[],omittedItems:ContextPacketOmission[]=[];const deliveryItems:any[]=[];let estimatedNewTokens=0,estimatedDuplicateTokensAvoided=0;
  const maxTokens=Math.min(options.maximumEstimatedTokens??DEFAULT_ESCALATION_LIMITS.maximumEstimatedTokensPerEscalation,session.remainingEstimatedTokens),maxItems=options.maximumItems??DEFAULT_ESCALATION_LIMITS.maximumItemsPerEscalation,mandatory=new Set(options.mandatoryCoverage??[]),covered=new Set<ContextCoverageCategory>();let additional=0;
  for(const candidate of candidates){const item=candidate.item;const duplicate=byVersion.get(item.id)??byHash.get(item.content_hash);if(duplicate){activeReferences.push({contextItemVersionId:item.id,contentHash:item.content_hash,sourcePath:item.source_path,title:item.title??undefined,estimatedTokens:candidate.estimatedTokens});estimatedDuplicateTokensAvoided+=candidate.estimatedTokens;deliveryItems.push({contextItemVersionId:item.id,role:"active_reference",estimatedTokens:candidate.estimatedTokens,contentHash:item.content_hash,presenceState:"active",duplicateOfDeliveryId:duplicate.delivery_id});for(const category of candidate.coverageCategories)covered.add(category);continue;}if(item.valid_to_commit_exclusive!==null||item.staleness_status==="stale"){omittedItems.push({contextItemVersionId:item.id,title:item.title??item.id,reason:item.valid_to_commit_exclusive!==null?"historical":"stale",estimatedTokens:candidate.estimatedTokens});continue;}if(candidate.score<(options.minimumCandidateScore??0)&&!candidate.coverageCategories.some(category=>mandatory.has(category))){omittedItems.push({contextItemVersionId:item.id,title:item.title??item.id,reason:"low_score",estimatedTokens:candidate.estimatedTokens});continue;}const required=candidate.coverageCategories.some(category=>mandatory.has(category)&&!covered.has(category));if(newItems.length>=maxItems||estimatedNewTokens+candidate.estimatedTokens>maxTokens){omittedItems.push({contextItemVersionId:item.id,title:item.title??item.id,reason:"budget",estimatedTokens:candidate.estimatedTokens});if(required)additional=Math.max(additional,candidate.estimatedTokens-(maxTokens-estimatedNewTokens));continue;}newItems.push({candidate,content:item.compiled_content??item.content,truncated:false});deliveryItems.push({contextItemVersionId:item.id,role:"new",estimatedTokens:candidate.estimatedTokens,contentHash:item.content_hash,presenceState:"active"});estimatedNewTokens+=candidate.estimatedTokens;for(const category of candidate.coverageCategories)covered.add(category);}
  const required=session.task.requiredCoverage.filter(entry=>entry.required).map(entry=>entry.category),coverageRemaining=required.filter(category=>!covered.has(category)&&!active.some(item=>candidates.some(c=>c.item.id===item.context_item_version_id&&c.coverageCategories.includes(category))));const packet:DeltaContextPacket={id:crypto.randomUUID(),sessionId:session.id,stage:options.stage,newItems,activeReferences,restoredItems:[],omittedItems,estimatedNewTokens,estimatedRestoredTokens:0,estimatedDuplicateTokensAvoided,coverageAdded:[...covered],coverageRemaining,trigger:options.trigger,strategyId:STRATEGY_ID,strategyVersion:STRATEGY_VERSION,decisionReasons:options.reasons,incomplete:coverageRemaining.length>0&&additional>0,...(additional>0?{additionalEstimatedTokensRequired:additional}:{})};
  const delivery=this.sessions.recordDelivery({sessionId:session.id,stage:options.stage,trigger:{type:options.trigger},reason:options.reason,items:deliveryItems,coverageAdded:packet.coverageAdded,coverageRemaining,estimatedDuplicateTokensAvoided,expectedSnapshot:options.currentSnapshot,signalId:options.signalId,decision:packet});return {...packet,id:delivery.id};
 }
}
