import type { ContextItemVersion, IndexSnapshotIdentity } from "./context-domain.js";

export type ContextItemKind = "file" | "function" | "method" | "class" | "constructor" | "interface" | "type" | "enum" | "constant" | "import" | "export" | "test" | "heading" | "configuration" | "table" | "index" | "view" | "trigger" | "migration" | "constraint" | "unknown";
export interface PurposeEvidence { text: string; source: "jsdoc" | "leading_comment" | "symbol_name" | "package_metadata" | "unknown" }
export interface ContextProvenance { repositoryId: number; sourcePath: string; sourceStartLine: number; sourceEndLine: number; extractor: string; snapshot: IndexSnapshotIdentity; confidence: "high" | "medium" | "low" }
export interface TypeScriptContextMetadata { declarationKind: string; exported: boolean; defaultExport: boolean; async: boolean; static: boolean; parentSymbol?: string; parameters?: string[]; returnType?: string; importedModules?: string[]; referencedIdentifiers?: string[] }
export type ConstraintKind = "architecture" | "security" | "privacy" | "compatibility" | "operational" | "testing";
export interface ContextItemMetadata { packageName?: string; purpose: PurposeEvidence; headingPath?: string[]; relatedTests?: string[]; importantImports?: string[]; constraintKind?: ConstraintKind; authoritySource?: string; parseConfidence?: "high" | "medium" | "low"; typescript?: TypeScriptContextMetadata; [key: string]: unknown }
export type ContextRelationshipKind = "contains" | "imports" | "exports" | "tests" | "configures" | "depends_on" | "implements" | "extends" | "documented_by" | "supersedes" | "renamed_from" | "derived_from";
export interface ContextRelationshipEvidence { sourcePath: string; sourceStartLine?: number; sourceEndLine?: number; description: string }
export interface ContextRelationshipCandidate { targetLogicalKey: string; kind: ContextRelationshipKind; confidence: "high" | "medium" | "low"; evidence: ContextRelationshipEvidence }
export interface PersistedContextRelationship { id: string; sourceContextItemId: string; targetContextItemId: string; kind: ContextRelationshipKind; confidence: "high" | "medium" | "low"; evidence: ContextRelationshipEvidence }
export interface RepositoryMetadata { name: string; packageName?: string; packageByPath?: Record<string, string>; testCommand?: string }
export interface ExtractedContextCandidate { name: string; kind: string; content: string; startLine: number; endLine: number; parentSymbol?: string; metadata?: Record<string, unknown>; purpose?: PurposeEvidence; relationships?: ContextRelationshipCandidate[] }
export interface ContextCompilationInput { repositoryId: number; repositoryRoot: string; sourcePath: string; language: string; sourceContent: string; snapshot: IndexSnapshotIdentity; extractedCandidates: ExtractedContextCandidate[]; repositoryMetadata: RepositoryMetadata }
export interface CompiledContextItem { logicalKey: string; kind: ContextItemKind; title: string; content: string; contextualHeader: string; compiledContent: string; sourcePath: string; sourceStartLine: number; sourceEndLine: number; symbolName?: string; parentSymbol?: string; language: string; contentHash: string; sourceFileHash: string; sourceBlobHash?: string; provenance: ContextProvenance; metadata: ContextItemMetadata; relationships: ContextRelationshipCandidate[] }
export interface ContextCompiler { compile(input: ContextCompilationInput): Promise<CompiledContextItem[]> }
export type TaskClass = "documentation" | "local_bug" | "cross_file_change" | "test_repair" | "configuration" | "dependency_update" | "database_migration" | "security_sensitive" | "performance" | "refactor" | "new_feature" | "repository_navigation" | "unknown";
export type ContextCoverageCategory = "implementation" | "public_contract" | "tests" | "configuration" | "architecture" | "security_constraint" | "database_schema" | "rollback" | "dependency" | "documentation" | "historical_episode" | "repository_state";
export interface ContextCoverageRequirement { category: ContextCoverageCategory; required: boolean; reason: string; maximumItems?: number }
export interface TaskAnalysis { originalTask: string; normalizedTask: string; taskClass: TaskClass; classificationReasons: string[]; mentionedPaths: string[]; mentionedSymbols: string[]; mentionedPackages: string[]; keywords: string[]; likelyLanguages: string[]; requiredCoverage: ContextCoverageRequirement[]; riskLevel: "low" | "medium" | "high" | "critical"; riskReasons: string[]; estimatedComplexity: "local" | "cross_file" | "cross_package" | "repository_wide" | "unknown" }
export interface TaskAnalyzer { analyze(task: string): TaskAnalysis }
export interface LexicalScoreEvidence { backend: "fts5" | "fallback_lexical"; rawScore: number; normalizedScore: number; normalizationMethod: string }
export interface RetrievalScoreComponents { exactSymbol: number; exactTitle: number; exactPath: number; lexical: number; contextualHeader: number; dependencyRelation: number; testRelation: number; architectureRelation: number; configurationRelation: number; priorEpisodeRelation: number; taskClassRelevance: number; riskCoverage: number; currentSnapshot: number; uncommittedPenalty: number; stalenessPenalty: number; historicalPenalty: number; tokenCostPenalty: number; duplicatePenalty: number }
export interface ContextCandidate { item: ContextItemVersion; score: number; components: RetrievalScoreComponents; reasons: string[]; coverageCategories: ContextCoverageCategory[]; estimatedTokens: number; provenance: ContextProvenance; lexicalEvidence: LexicalScoreEvidence }
export interface GraphExpansionBudget { maxDepth: number; maxNeighborsPerItem: number; maxEstimatedTokens: number }
export interface ContextPacketBudget { maxEstimatedTokens: number; maxItems: number; maxEstimatedTokensPerItem: number; orientationReserveRatio: number; requiredCoverageReserveRatio: number }
export interface ContextPacketItem { candidate: ContextCandidate; content: string; truncated: boolean }
export interface ContextPacketSection { items: ContextPacketItem[]; estimatedTokens: number }
export interface ContextPacketOmission { contextItemVersionId: string; title: string; reason: "budget" | "duplicate" | "diversity" | "stale" | "historical" | "low_score" | "oversized"; estimatedTokens: number }
export interface ContextCoverageReport { requirements: ContextCoverageRequirement[]; covered: ContextCoverageCategory[]; missing: ContextCoverageCategory[]; coverageEvidence: { category: ContextCoverageCategory; contextItemVersionIds: string[]; explanation: string }[]; complete: boolean; additionalEstimatedBudgetRequired?: number }
export interface CompiledContextPacket { id: string; repositoryId: number; snapshot: IndexSnapshotIdentity; task: TaskAnalysis; budget: ContextPacketBudget; orientation: ContextPacketSection; implementation: ContextPacketSection; escalationCandidates: ContextPacketSection; coverage: ContextCoverageReport; totalEstimatedTokens: number; omittedItems: ContextPacketOmission[]; complete: boolean; incompleteReasons: string[]; strategyVersion: string; generatedAt: string }
export interface SemanticIndexItem { id: string; text: string; metadata?: Record<string, unknown> }
export interface SemanticSearchOptions { limit: number }
export interface SemanticSearchResult { id: string; score: number }
export interface SemanticRetriever { readonly id: string; readonly model?: string; isAvailable(): Promise<boolean>; index(items: SemanticIndexItem[]): Promise<void>; search(query: string, options: SemanticSearchOptions): Promise<SemanticSearchResult[]> }
