import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { openDatabase, migrate, type Db } from "../src/connection.js";
import { ContextSessionRepository, ContextItemRepositoryMismatchError } from "../src/repositories/context-session-repository.js";
import type { ContextControlSignal, IndexSnapshotIdentity } from "@continuum/shared";
const snapshot:IndexSnapshotIdentity={snapshot_kind:"worktree",base_commit_hash:"abc",worktree_hash:"a".repeat(64),dirty:true};
describe("ContextSessionRepository",()=>{let db:Db;beforeEach(()=>{db=openDatabase(":memory:");migrate(db);const time=new Date().toISOString();db.prepare("INSERT INTO repositories(id,canonical_path,name,created_at,updated_at) VALUES(1,'/one','one',?,?),(2,'/two','two',?,?)").run(time,time,time,time);for(const [repo,id] of [[1,"v1"],[2,"foreign"]] as const){db.prepare("INSERT INTO context_items(id,repository_id,kind,logical_key,created_at) VALUES(?,?,?,?,?)").run(`i-${id}`,repo,"function",id,time);db.prepare(`INSERT INTO context_item_versions(id,context_item_id,content,title,source_path,source_start_line,source_end_line,language,content_hash,source_blob_hash,valid_from_commit,indexed_at,staleness_status,provenance_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,`i-${id}`,id,id,`${id}.ts`,1,1,"typescript",`hash-${id}`,`blob-${id}`,snapshot.base_commit_hash,time,"uncommitted",JSON.stringify({snapshot}));}});afterEach(()=>db.close());
 it("persists atomic deliveries, signal decisions, budgets and completion transitions",()=>{const repo=new ContextSessionRepository(db);const row=repo.create({repositoryId:1,taskText:"task",taskAnalysisJson:JSON.stringify({requiredCoverage:[]}),snapshot,strategyId:"minimum-safe-progressive-v1",strategyVersion:"1",maximumEstimatedTokens:100});repo.activate(row.id);const signal=repo.recordSignal(row.id,{type:"missing_coverage",categories:["tests"]});repo.recordDelivery({sessionId:row.id,stage:"escalation",trigger:{type:"missing_coverage"},reason:"test",items:[{contextItemVersionId:"v1",role:"new",estimatedTokens:20,contentHash:"hash-v1",presenceState:"active"}],coverageAdded:["implementation"],coverageRemaining:["tests"],estimatedDuplicateTokensAvoided:0,expectedSnapshot:snapshot,signalId:signal.id,decision:{ok:true}});expect(repo.listDeliveries(row.id)).toHaveLength(1);expect(repo.listDeliveryItems(repo.listDeliveries(row.id)[0]!.id)[0]?.delivery_role).toBe("new");expect(repo.findRequired(row.id).remaining_estimated_tokens).toBe(80);expect(repo.listSignals(row.id)[0]?.decision_json).toBe('{"ok":true}');repo.complete(row.id,"completed");expect(repo.findActiveItems(row.id)).toHaveLength(0);expect(repo.listPresenceTransitions(row.id).map((item:any)=>item.new_state)).toEqual(["active","expired"]);});
 it("rolls back a delivery containing foreign-repository context",()=>{const repo=new ContextSessionRepository(db);const row=repo.activate(repo.create({repositoryId:1,taskText:"task",taskAnalysisJson:"{}",snapshot,strategyId:"minimum-safe-progressive-v1",strategyVersion:"1",maximumEstimatedTokens:100}).id);expect(()=>repo.recordDelivery({sessionId:row.id,stage:"escalation",trigger:{},reason:"foreign",items:[{contextItemVersionId:"v1",role:"new",estimatedTokens:10,contentHash:"hash-v1",presenceState:"active"},{contextItemVersionId:"foreign",role:"new",estimatedTokens:10,contentHash:"hash-foreign",presenceState:"active"}],coverageAdded:[],coverageRemaining:[],estimatedDuplicateTokensAvoided:0,expectedSnapshot:snapshot,decision:{}})).toThrow(ContextItemRepositoryMismatchError);expect(repo.listDeliveries(row.id)).toHaveLength(0);expect(repo.findRequired(row.id).delivered_estimated_tokens).toBe(0);});
});
